Rails:
  Enabled: true

Metrics/LineLength:
  Max: 80

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false
