default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: palace_development

test:
  <<: *default
  database: palace_test

production:
  <<: *default
  database: palace_production
  username: palace
  password: <%= ENV['PALACE_DATABASE_PASSWORD'] %>
